"""Reference list of known venture capital and growth equity firms."""

VC_FIRMS: set[str] = {
    "sequoia",
    "sequoia capital",
    "andreessen horowitz",
    "a16z",
    "kleiner perkins",
    "accel",
    "accel partners",
    "benchmark",
    "bessemer",
    "bessemer venture partners",
    "greylock",
    "general catalyst",
    "lightspeed",
    "lightspeed venture partners",
    "tiger global",
    "general atlantic",
    "insight partners",
    "warburg pincus",
    "kkr",
    "blackstone",
    "silver lake",
    "vista equity",
    "battery ventures",
    "index ventures",
    "new enterprise associates",
    "nea",
    "founders fund",
    "union square ventures",
    "usv",
    "spark capital",
    "matrix partners",
    "redpoint",
    "redpoint ventures",
    "first round capital",
    "felicis",
    "felicis ventures",
    "coatue",
    "coatue management",
    "dragoneer",
    "dragoneer investment group",
    "softbank",
    "softbank vision fund",
    "google ventures",
    "gv",
    "intel capital",
    "salesforce ventures",
    "qualcomm ventures",
    "norwest venture partners",
    "norwest",
    "american family ventures",
    "idc ventures",
    "thoma bravo",
    "francisco partners",
    "advent international",
    "apax partners",
    "permira",
    "hg capital",
    "openview",
    "openview venture partners",
    "scale venture partners",
    "menlo ventures",
    "innovation endeavors",
}


def is_vc_firm(name: str) -> bool:
    """Return True if name (case-insensitive substring match) matches a known VC firm."""
    name_lower = name.lower()
    return any(firm in name_lower for firm in VC_FIRMS)
